name: submodule update

on:
  workflow_dispatch:
    inputs:
      LMS_branch:
        description: 'lms'     
        required: true
        default: 'staging'
        
      scorm_branch:
        description: 'scorm'     
        required: true
        default: 'staging'
        
      frontend_branch:
        description: 'frontend'     
        required: true
        default:         
      git_username:
        required: true

env:
  CI: false
  TOKEN: ${{ github.event.inputs.token }}
  USERNAME: ${{ github.event.inputs.git_username }}
  LMS_Branch: ${{ github.event.inputs.LMS_branch }}
  scorm_Branch: ${{ github.event.inputs.scorm_branch }}
  frontend_Branch: ${{ github.event.inputs.frontend_branch }}

jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo $LMS_Branch,$scorm_Branch
        
