name: submodule update

on:

  workflow_dispatch:
    inputs:
      LMS_branch:
        description: 'lms'     
        required: true
        default: 'staging'
        type: choice
        description: 'Choose LMS BRANCH name'
       
      scorm_branch:
        description: 'scorm'     
        required: true
        default: 'staging'
        type: choice
        description: 'Choose SCORM BRANCH name'
      frontend_branch:
        description: 'frontend'     
        required: true
        default: 'staging'
        type: choice
        description: 'Choose frontend BRANCH name'            
      token:
        description: 'Token'     
        required: true
      git_username:
        description: 'Username for git'
        required: true


      
      
env:
  CI: false
  TOKEN: ${{ github.event.inputs.token }}
  USERNAME: ${{ github.event.inputs.git_username }}
  LMS_Branch: ${{ github.event.inputs.LMS_branch }}
  scorm_Branch: ${{ github.event.inputs.scorm_branch }}
  frontend_Branch: ${{ github.event.inputs.frontend_branch }}

jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo $LMS_Branch,$scorm_Branch
        
