name: github code push

on:

  workflow_dispatch:
    inputs:
      branch1:
        description: 'Branch name for LMS'
        required: true
      branch2:
        description: 'Branch name for SCORM'
        required: true
      branch3:
        description: 'Branch name for Frontend'
        required: true
      Username:
        description: 'Enter your github user'
        required: true
jobs:
  master-build:
    name: condition
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.branch1 == 'master' }}
    steps:
     - name: print hello
       run: echo "skip"
     - name: Show GitHub context   
       env: 
         GITHUB_CONTEXT: ${{ toJson(github) }}   
       run: echo "$GITHUB_CONTEXT"
  build:
    name: clone repo
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.branch1 != 'master' }}
    steps:
     - name: Check out code
       uses: actions/checkout@v3
       
     - name: Show GitHub context   
       env: 
         GITHUB_CONTEXT: ${{ toJson(github) }}   
       run: echo "$GITHUB_CONTEXT"
         
     - name: Clone LMS
       run: git clone --branch ${{ github.event.inputs.branch1 }} https://${{ github.event.inputs.Username }}:${{ secrets.TOKEN }}@github.com/sahid-org-1/test1.git
     - name: Clone LMS
       run: | 
         ls
#         cd ./test1/app/repos/
#         rm -rf git_task1 github-webhook
     - name: Clone frontend
       run: |
         ls
         git clone --branch ${{ github.event.inputs.branch2 }} https://${{ github.event.inputs.Username }}:${{ secrets.TOKEN }}@github.com/SahidTft/git_task1.git
       
     - name: Clone scorm
       run: git clone --branch ${{ github.event.inputs.branch3 }} https://${{ github.event.inputs.Username }}:${{ secrets.TOKEN }}@github.com/SahidTft/github-webhook.git

     - name: Add changes
       shell: bash
       run: |
        ls
        git add .

     - name: Commit changes
       shell: bash
       run: |
        git config --global user.email "khan.sahid@tftus.com"
        git config --global user.name "${{ github.event.inputs.Username }}"
        git commit -m "Update code"

     - name: Push changes
       uses: ad-m/github-push-action@master
       with:
        github_token: ${{ secrets.TOKEN }}
        branch: ${{ github.ref }}
        force: true
