name: github submodule update
on:
  push:
    inputs:
      branch1:
        description: 'Branch name for repository 1'
        required: true
      branch2:
        description: 'Branch name for repository 2'
        required: true
      branch3:
        description: 'Branch name for repository 3'
        required: true
jobs:
  clone_repos:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Clone Repository 1
      run: git clone --branch ${{ inputs.branch1 }} https://github.com/sahid-org-1/test1.git repo1

    - name: Clone Repository 2
      run: git clone --branch ${{ inputs.branch2 }} https://github.com/SahidTft/github-webhook.git repo2

    - name: Clone Repository 3
      run: git clone --branch ${{ inputs.branch3 }} https://github.com/SahidTft/git_task1 repo3
